const data = {
  products: [
    {
      name: "Lápis",
      images: [
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
      ],
      videos: ["https://www.youtube.com/watch?v=EW7m2WIvFgQ"],
      price: 25.99,
      description: "High quality product",
      category: "Material escolar",
      tags: ["lápis", "material", "escolar"],
      quantityInStock: 2,
    },
    {
      name: "Caneta Azul",
      images: [
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
      ],
      videos: [],
      price: 55.99,
      description: "High quality product",
      category: "Material escolar",
      tags: ["caneta", "material", "escolar"],
      quantityInStock: 25,
    },
    {
      name: "Alicate",
      images: [
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
      ],
      videos: [],
      price: 2.5,
      description: "High quality product",
      category: "Material escolar",
      tags: ["caneta", "material", "escolar"],
      quantityInStock: 10,
    },
  ],
};
export default data;
