export const TOKEN_LOGIN_REQUEST = "TOKEN_LOGIN_REQUEST";

export const TOKEN_REGISTER_REQUEST = "TOKEN_REGISTER_REQUEST";

export const TOKEN_SUCCESS = "TOKEN_SUCCESS";
export const TOKEN_FAIL = "TOKEN_FAIL";

export const LOGOUT = "LOGOUT";
