const data = {
  products: [
    {
      _id: "0",
      name: "Lápis",
      images: [
        "/images/OIP.jpg",
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
        "/images/OIP.jpg",
        "/images/Caneta.jpg",
      ],
      videos: ["https://www.youtube.com/watch?v=EW7m2WIvFgQ"],
      price: 25.99,
      description: "High quality product",
      category: "Material escolar",
      tags: ["lápis", "material", "escolar"],
      productInStock: 2,
    },
    {
      _id: "1",
      name: "Caneta Azul",
      images: ["/images/Caneta.jpg", "/images/Caneta.jpg"],
      videos: [],
      price: 55.99,
      description: "High quality product",
      category: "Material escolar",
      tags: ["caneta", "material", "escolar"],
      productInStock: 25,
    },
    {
      _id: "2",
      name: "Lápis",
      images: ["/images/OIP.jpg", "/images/OIP.jpg"],
      videos: [],
      price: 25.99,
      description: "High quality product",
      category: "Material escolar",
      tags: ["lápis", "material", "escolar"],
      productInStock: 10,
    },
    {
      _id: "3",
      name: "Caneta Azul",
      images: ["/images/Caneta.jpg", "/images/Caneta.jpg"],
      videos: [],
      price: 55.99,
      description: "High quality product",
      category: "Material escolar",
      tags: ["caneta", "material", "escolar"],
      productInStock: 0,
    },
  ],
};
export default data;
